
### 1. 인가코드 발급
GET https://openapi.imweb.me/oauth2/authorize?responseType=code&clientId=b9b88ca4-edc8-48f6-b058-8debda8d1987&redirectUri=https://api-dev.biocom.ai.kr/api/auth/redirect&scope=site-info%3Awrite%20member-info%3Aread%20promotion%3Awrite%20community%3Aread%20product%3Aread%20order%3Aread%20payment%3Aread&siteCode=S20190715619285c855898


### 3. 바이오컴 회원 목록 조회
GET https://openapi.imweb.me/member-info/members?page=1&limit=10&unitCode=u201907155d2bfcd44e8de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### 3-1 회원 상세 조회
GET https://openapi.imweb.me/member-info/members/yejisydneyjeong@gmail.com?unitCode=u201907155d2bfcd44e8de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### 1755754174
### 5. 주문목록
GET https://openapi.imweb.me/orders?page=1&limit=10&unitCode=u201907155d2bfcd44e8de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### 7. 상품 구매평 목록 조회
GET https://openapi.imweb.me/community/review?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### 8. 상품 목록
GET https://openapi.imweb.me/products?page=1&limit=100&unitCode=u201907155d2bfcd44e8de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### 9. 상품 상세
GET https://openapi.imweb.me/products/172?unitCode=u201907155d2bfcd44e8de
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaXRlQ29kZSI6IlMyMDE5MDcxNTYxOTI4NWM4NTU4OTgiLCJhcHBDb2RlIjoiZ2EyMDI1MDgyMDZhMTkxZjI5MzZlNTgiLCJ1bml0Q29kZSI6WyJ1MjAxOTA3MTU1ZDJiZmNkNDRlOGRlIl0sInNjb3BlIjpbInNpdGUtaW5mbzp3cml0ZSIsIm1lbWJlci1pbmZvOnJlYWQiLCJwcm9tb3Rpb246d3JpdGUiLCJjb21tdW5pdHk6cmVhZCIsInByb2R1Y3Q6cmVhZCIsIm9yZGVyOnJlYWQiLCJwYXltZW50OnJlYWQiXSwic2l0ZVZlcnNpb24iOiJwcm8iLCJpYXQiOjE3NTYxOTM0NTgsImV4cCI6MTc1NjIwMDY1OH0.U4wil35HHJ8vvMQAW51QTWoz80oxU6IceeGpPJN9A5Y

### yejisydneyjeong@gmail.com